[workspace]

[[package]]
name = "lux-rs"
release = false
publish = false

[[package]]
name = "sensor-forecast"
release = false
publish = false

[[package]]
name = "sensor-room-therm"
release = false
publish = false

[[package]]
name = "mqtt-to-dbus"
release = false
publish = false
